.TH RIC "1" "May 2020" "User Commands"
.SH NAME
ric \- RCI Internet Command
.SH SYNOPSIS
.B ric
[-h] [-v] [[\fI\,HOSTNAME\/\fR]:[\fI\,PORT\/\fR]]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Various utilities described in
\fBSanguino, J., "A Quick Guide to Networking Software", 5th Edition, Feb 2020\fR
.TP
\fB\-h\fR,
Display help and exit
.TP
\fB\-v\fR,
Display version and exit
.TP
\fB\-n\fR
Display hostname: Task 1
.TP
\fB\-w\fR,
Display nslookup: Task 2
.TP
\fB\-u\fR,
udp_client, that sends a "Hello!", Task 3, 4, 5
.TP
\fB\-t\fR,
tcp_client, that sends a "Hello!", Task 6, 7, 8
.TP
\fB\-lu\fR,
udp_server, a simple udp echo server, Task 9
.TP
\fB\-lt\fR,
tcp_server, a simple tcp echo server, Task 10, 11, 12
.SH AUTHOR
.PP
Written by Carlos Pinto Machado, and Mariana Carvalho.
.PP
Based in
\fBSanguino, J., "A Quick Guide to Networking Software", 5th Edition, Feb 2020\fR
.SH COPYRIGHT
.PP
Copyright \(co 2020 Carlos Pinto Machado, Mariana Carvalho
.PP
License MIT
